2025-04-26 23:26:00,438 INFO    MainThread:3640936 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_setup.py:_flush():68] Configure stats pid to 3640936
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_setup.py:_flush():68] Loading settings from /home/e210/.config/wandb/settings
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_setup.py:_flush():68] Loading settings from /home/e210/git/doseae/wandb/settings
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/e210/git/doseae/wandb/run-20250426_232600-e1w0ew15/logs/debug.log
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/e210/git/doseae/wandb/run-20250426_232600-e1w0ew15/logs/debug-internal.log
2025-04-26 23:26:00,439 INFO    MainThread:3640936 [wandb_init.py:init():852] calling init triggers
2025-04-26 23:26:00,440 INFO    MainThread:3640936 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'dataset': {'data_dir': '/media/e210/HD81/Adhvaith_datasets/nsclc_public', 'data_pkl': '/media/e210/HD81/Adhvaith_datasets/results/datasets/test_20/volumes_dataset.pkl', 'train_ratio': 0.8, 'val_ratio': 0.1, 'test_ratio': 0.1, 'input_size': [64, 64, 64], 'input_size_2d': 256, 'patch_size': [64, 64], 'patch_size_3d': [16, 64, 64], 'use_single_file': True, 'data_file': '/media/e210/HD81/Adhvaith_datasets/results/datasets/test_20/volumes_dataset.pkl', 'test_mode': True, 'n_test_samples': 20}, 'preprocessing': {'normalize': True, 'normalize_method': '95percentile', 'percentile_norm': 95, 'voxel_spacing': [2, 2, 2], 'resize_to': [128, 128, 64], 'unit_type': 'voxels', 'extract_slices': False, 'slice_extraction': 'informative', 'non_zero_threshold': 0.05, 'num_workers': 8, 'batch_size': 1000, 'use_tanh_output': False}, 'transforms': {'augment': True, 'rotate': True, 'flip': True, 'adjust_brightness': True, 'random_crop': False, 'random_noise': False}, 'patch_extraction': {'enable': False, 'patch_dimension': '3D', 'patch_size': [50, 50, 50], 'patch_unit_type': 'voxels', 'threshold': 0.01, 'max_patches_per_slice': 100, 'max_patches_per_volume': 500, 'random_state': 42}, 'model': {'type': 'resnet_ae', 'is_2d': False, 'latent_dim': 132, 'in_channels': 1, 'base_filters': 36, 'bottleneck_filters': 256, 'dropout_rate': 0.3}, 'hyperparameters': {'learning_rate': 1.3783237455007187e-05, 'batch_size': 32, 'epochs': 100, 'early_stopping_patience': 10, 'weight_decay': 0.0007886714129990489, 'beta': 1.0}, 'training': {'optimizer': 'adam', 'scheduler': 'reduce_on_plateau', 'loss': 'mse', 'gpu_id': 0, 'seed': 42, 'grad_clip': 0.1, 'non_zero_loss': False, 'accumulation_steps': 1}, 'wandb': {'use_wandb': True, 'project_name': 'dose_distribution_autoencoder', 'entity': 'pgsalome', 'name': 'trial_2', 'group': 'resumed_opt_20250426_232558', 'tags': ['optimization', 'trial_2']}, 'optuna': {'use_optuna': False, 'n_trials': 50, 'timeout': 86400, 'direction': 'minimize', 'sampler': 'tpe', 'pruner': 'median'}, 'output': {'model_dir': '/media/e210/HD81/Adhvaith_datasets/results/models', 'log_dir': '/media/e210/HD81/Adhvaith_datasets/results/logs', 'results_dir': '/media/e210/HD81/Adhvaith_datasets/results'}, 'trial_num': 2, '_wandb': {}}
2025-04-26 23:26:00,440 INFO    MainThread:3640936 [wandb_init.py:init():893] starting backend
2025-04-26 23:26:00,440 INFO    MainThread:3640936 [wandb_init.py:init():897] sending inform_init request
2025-04-26 23:26:00,483 INFO    MainThread:3640936 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-26 23:26:00,484 INFO    MainThread:3640936 [wandb_init.py:init():907] backend started and connected
2025-04-26 23:26:00,488 INFO    MainThread:3640936 [wandb_init.py:init():1002] updated telemetry
2025-04-26 23:26:00,520 WARNING MainThread:3640936 [wandb_init.py:init():1654] [no run ID] interrupted
Traceback (most recent call last):
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1650, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1015, in init
    run._populate_git_info()
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1731, in _populate_git_info
    self._settings.git_commit = repo.last_commit
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/wandb/sdk/lib/gitlib.py", line 119, in last_commit
    if not self.repo.head or not self.repo.head.is_valid():
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 514, in is_valid
    self.object  # noqa: B018
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/objects/base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/db.py", line 41, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/cmd.py", line 1678, in get_object_header
    cmd = self._get_persistent_cmd("cat_file_header", "cat_file", batch_check=True)
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/cmd.py", line 1654, in _get_persistent_cmd
    cmd = self._call_process(cmd_name, *args, **options)
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/cmd.py", line 1599, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/e210/git/doseae/venv/lib/python3.8/site-packages/git/cmd.py", line 1262, in execute
    proc = safer_popen(
  File "/home/e210/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/e210/anaconda3/lib/python3.8/subprocess.py", line 1658, in _execute_child
    part = os.read(errpipe_read, 50000)
KeyboardInterrupt
2025-04-26 23:26:01,066 INFO    MsgRouterThr:3640936 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
